version: '3.8'

services:
  hotel-natraj-app:
    build: .
    container_name: hotel-natraj-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.natraj-hotel.rule=Host(`natrajhotels.obsidiansix.com`)"
      - "traefik.http.routers.natraj-hotel.entrypoints=websecure"
      - "traefik.http.routers.natraj-hotel.tls.certresolver=myresolver"
      - "traefik.http.services.natraj-hotel.loadbalancer.server.port=3000"
    volumes:
      - /var/www/natraj-hotel-data:/app/public/uploads
    networks:
      - web

networks:
  web:
    external: true
    name: web_network